language: ruby
rvm:
- 2.1

script: jekyll build

branches:
  only:
    - gh-pages
    - /^.*$/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  
sudo: false
