# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pražský Tyrannus Hall
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Webové stránky vysokoškolského učednického společenství mladých křesťanů v Praze.
  Informace o naší vizi, historii a pro uchazeče o vstup.
baseurl: "/pth-cz.net" # the subpath of your site, e.g. /blog
url: "https://yetty.github.io"

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

