# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pražský Tyrannus Hall
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Vysokoškolské učednického společenství mladých křesťanů v Praze.
  Naše vize, historie a informace pro uchazeče o vstup.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pth-cz.net"

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

exclude: [vendor]
sass:
  sass_dir: _sass
  style: compressed

# Defaults settings
defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post" # overrides previous default layout
